name: readthedocs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - numpy<=1.24.0 #avoid errors caused by 1.24
  - simba>=1.1
  - pandoc>=2.14
  - pip:
    - sphinx>=3.0
    - sphinx-rtd-theme>=0.5
    - nbsphinx>=0.8
